<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Kapil" failures="1" tests="1" name="Default test(failed)" time="6.701" errors="0" timestamp="2023-10-29T20:09:59 IST">
  <testcase classname="testCases.LoginPageTest" name="loginToAppTest" time="1.436">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;6&amp;gt; but was:&amp;lt;https://www.saucedemo.com/inventory.html&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<6> but was:<https://www.saucedemo.com/inventory.html>
at testCases.LoginPageTest.loginToAppTest(LoginPageTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginToAppTest -->
  <testcase classname="testCases.LoginPageTest" name="verifyURLofApplication" time="0.0">
    <ignored/>
  </testcase> <!-- verifyURLofApplication -->
  <testcase classname="testCases.LoginPageTest" name="verifyTitleOfApplication" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitleOfApplication -->
</testsuite> <!-- Default test(failed) -->
